<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Title>LightMQ.Storage.Redis</Title>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="StackExchange.Redis" Version="2.8.31" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LightMQ\LightMQ.csproj" />
    </ItemGroup>

</Project>