<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latestmajor</LangVersion>
        <Title>LightMQ.Storage.MongoDB</Title>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\LightMQ\LightMQ.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MongoDB.Driver" Version="3.3.0" />
    </ItemGroup>

</Project>
